import java.time.Year;

/**
 * Represents a single movie entity within the Data Management System (DMS).
 * <p>
 * Each {@code Movie} object encapsulates metadata such as title, release year,
 * director, rating, runtime, votes, and whether it has been watched.
 * </p>
 *
 * <p><b>Role in the System:</b></p>
 * Acts as the data model for the application. It is used by
 * {@link MovieDatabaseManager} for database storage/retrieval,
 * and by the GUI classes (e.g., {@link MovieGUI}, {@link MovieDialogGUI})
 * to display and edit movie data.
 *
 * <p><b>Validation:</b></p>
 * This class includes input validation in methods such as {@link #fromCSV(String)}
 * and the GUI components that instantiate it.
 *
 * <p><b>Example Usage:</b></p>
 * <pre>{@code
 * Movie m = new Movie("Inception", 2010, "Christopher Nolan", 8.8, 148, 2200000, true);
 * System.out.println(m.prettyPrint());
 * }</pre>
 *
 * @author YourName
 * @version 1.0
 */
public class Movie {

    /** Unique identifier of the movie (primary key in the database). */
    private int id;

    private String title;
    private int year;
    private String director;
    private double rating;         // Range: 0.0 - 10.0
    private int runtimeMinutes;    // Must be positive
    private int votes;             // Non-negative
    private boolean watched;

    // ==================== CONSTRUCTORS ====================

    /**
     * Creates a {@code Movie} object with all fields, including database ID.
     * <p>
     * Typically used when loading data from the database where the ID is already known.
     * </p>
     *
     * @param id             unique identifier from the database
     * @param title          movie title
     * @param year           release year
     * @param director       movie director
     * @param rating         IMDb-style rating (0.0–10.0)
     * @param runtimeMinutes runtime duration in minutes
     * @param votes          number of votes received
     * @param watched        whether the movie has been watched
     */
    public Movie(int id, String title, int year, String director, double rating, int runtimeMinutes, int votes, boolean watched) {
        this.id = id;
        this.title = title;
        this.year = year;
        this.director = director;
        this.rating = rating;
        this.runtimeMinutes = runtimeMinutes;
        this.votes = votes;
        this.watched = watched;
    }

    /**
     * Creates a {@code Movie} object for new entries without a database ID.
     * <p>
     * The ID is usually auto-generated by the database when the record is inserted.
     * </p>
     *
     * @param title          movie title
     * @param year           release year
     * @param director       movie director
     * @param rating         IMDb-style rating (0.0–10.0)
     * @param runtimeMinutes runtime duration in minutes
     * @param votes          number of votes received
     * @param watched        whether the movie has been watched
     */
    public Movie(String title, int year, String director, double rating, int runtimeMinutes, int votes, boolean watched) {
        this.title = title;
        this.year = year;
        this.director = director;
        this.rating = rating;
        this.runtimeMinutes = runtimeMinutes;
        this.votes = votes;
        this.watched = watched;
    }

    /** Default no-argument constructor. */
    public Movie() {}

    // ==================== GETTERS ====================

    /** @return the unique ID of the movie */
    public int getId() { return id; }

    /** @return the movie title */
    public String getTitle() { return title; }

    /** @return the release year */
    public int getYear() { return year; }

    /** @return the movie director */
    public String getDirector() { return director; }

    /** @return the movie rating (0–10 scale) */
    public double getRating() { return rating; }

    /** @return the runtime in minutes */
    public int getRuntimeMinutes() { return runtimeMinutes; }

    /** @return the total number of votes */
    public int getVotes() { return votes; }

    /** @return {@code true} if the movie has been watched; otherwise {@code false} */
    public boolean isWatched() { return watched; }

    // ==================== SETTERS ====================

    public void setId(int id) { this.id = id; }
    public void setTitle(String title) { this.title = title; }
    public void setYear(int year) { this.year = year; }
    public void setDirector(String director) { this.director = director; }
    public void setRating(double rating) { this.rating = rating; }
    public void setRuntimeMinutes(int runtimeMinutes) { this.runtimeMinutes = runtimeMinutes; }
    public void setVotes(int votes) { this.votes = votes; }
    public void setWatched(boolean watched) { this.watched = watched; }

    // ==================== METHODS ====================

    /**
     * Calculates a "scariness" score for the movie based on rating, votes, runtime, and watch status.
     * <p>
     * The formula considers several factors:
     * <ul>
     *   <li>Higher rating → higher scariness</li>
     *   <li>More votes → slightly higher scariness (up to a limit)</li>
     *   <li>Longer runtime (>120 min) → slightly higher score</li>
     *   <li>Watched movies → slightly less scary</li>
     * </ul>
     *
     * @return the calculated scariness score (rounded to one decimal place, range 0–10)
     */
    public double getScariness() {
        double score = rating;
        score += Math.min(votes / 500000.0, 2);
        if (runtimeMinutes > 120) score += 1;
        if (watched) score -= 1;
        score = Math.max(0, Math.min(10, score));
        return Math.round(score * 10.0) / 10.0;
    }

    /**
     * Returns a formatted string representation of the movie with key details.
     *
     * @return a user-friendly formatted string containing movie details
     */
    public String prettyPrint() {
        return String.format(
                "%s (%d)\nDirector: %s\nRating: %.1f\nRuntime: %d min\nVotes: %d\nWatched: %s\nScariness: %.1f",
                title, year, director, rating, runtimeMinutes, votes, watched ? "Yes" : "No", getScariness()
        );
    }

    /**
     * Converts the movie's information into a comma-separated format (CSV).
     * <p>
     * This can be used for exporting or backing up data.
     * </p>
     *
     * @return a CSV-formatted string representing this movie
     */
    @Override
    public String toString() {
        return String.format("%s,%d,%s,%.1f,%d,%d,%s",
                title, year, director, rating, runtimeMinutes, votes, watched);
    }

    /**
     * Creates a {@code Movie} object from a CSV-formatted string.
     * <p>
     * Expected CSV format:
     * {@code title,year,director,rating,runtimeMinutes,votes,watched}
     * </p>
     *
     * @param line the CSV line to parse
     * @return a new {@code Movie} object parsed from the given string
     * @throws IllegalArgumentException if the line is null, malformed, or contains invalid values
     */
    public static Movie fromCSV(String line) {
        if (line == null) throw new IllegalArgumentException("Line is null");

        String[] parts = line.split(",", -1);
        if (parts.length != 7) throw new IllegalArgumentException("Expected 7 fields but found " + parts.length);

        for (int i = 0; i < parts.length; i++) parts[i] = parts[i].trim();

        String title = parts[0];
        if (title.isEmpty()) throw new IllegalArgumentException("Title is empty");

        int year = Integer.parseInt(parts[1]);
        int currentYear = Year.now().getValue();
        if (year < 1888 || year > currentYear) throw new IllegalArgumentException("Invalid year");

        String director = parts[2];
        double rating = Double.parseDouble(parts[3]);
        int runtime = Integer.parseInt(parts[4]);
        int votes = Integer.parseInt(parts[5]);
        boolean watched = parts[6].equalsIgnoreCase("true") || parts[6].equalsIgnoreCase("yes");

        return new Movie(title, year, director, rating, runtime, votes, watched);
    }
}
